### ISSUE TITLE
Geno Group Hug softlocks

### ISSUE THREAD

**Issue by Niamek** [abyssonym/smrpg_gbarp#10]
So I did a group hug with Geno and guess what it softlocked. Maybe You should test the special attacks on Geno too to see if it softlocks...

![super mario rpg - legend of the seven stars usa 1480813151000](https://cloud.githubusercontent.com/assets/15385566/20863552/339790c0-b99c-11e6-8d15-b6716a7d52e1.png)

**Comment by abyssonym** [comment]
Seems like this one doesn't have much to do with Geno. The game will also freeze if Mallow uses Group Hug in the Bowyer fight. Mario can pull it off, though. Using Group Hug in some other battles seems to work fine, regardless of character. It even works fine in the Bowyer fight, if Bowyer doesn't have his buttons out. This might be a VRAM issue, where Bowyer & his buttons uses up a lot of memory, and for some reason Mallow and Geno using Group Hug is too much.

**Comment by abyssonym** [comment]
From https://github.com/abyssonym/smrpg_gbarp/issues/9

>Mario using Group Hug during the Axem Rangers fight caused a softlock. Hasn't happened in any other battles that I've observed. Bowser could use Group Hug in the same fight with no problems.

**Comment by abyssonym** [comment]
Decided to fix this by restricting Group Hug to Peach. https://github.com/abyssonym/smrpg_gbarp/commit/5d0c98dd6bb3430e6dcc778c8a2585951432b57f
