### ISSUE TITLE
Weird Sprite

### ISSUE THREAD

**Issue by Niamek** [abyssonym/smrpg_gbarp#11]
https://clips.twitch.tv/darbian/MotionlessRhinocerosNotATK

Happened in the randomizer race today to Darbian.

**Comment by Niamek** [comment]
Honestly I don't mind if it doesn't crash or softlocks the game. But I posted it here in case you don,t want this to appear. Feel free to close this if you don't think it should be fixed.

**Comment by abyssonym** [comment]
That's funny, I haven't seen those before. Yeah, I don't mind seeing weird things like this as long as it doesn't make the game unplayable. Thanks for letting me know anyway, though.
