### ISSUE TITLE
Getting experience after a battle in mushroom way and in Bowser's Castle

### ISSUE THREAD

**Issue by Niamek** [abyssonym/smrpg_gbarp#3]
So I redid a new seed.

SEED: 1473602340

In Bowser's castle during the intro, I could get experience there... In the original game, you don't get experience before getting to mushroom way.

In mushroom way (first room, where there is two paratroopa), fighting a goomba formation won't give you experience. Spikeys in Bandit's way neither.

I think it's related, but I'm not sure,..A fight with the first paratroopa ended prematurely.

**Comment by Niamek** [comment]
For the paratroopa concern, you need to meet the right formation I believe. There was the boss of the volcano in that formation.

**Comment by Niamek** [comment]
You can see that in the movie I provided in the issue I referenced. So you won't need to actually play the game to meet these issues.

**Comment by abyssonym** [comment]
It's not a problem to get experience before Mushroom Way, is it?

**Comment by Niamek** [comment]
No indeed. But I didn't think it was intentional, so I mentionned it. (Not to mention that if I recall correctly you can't access to the pause menu) The most problematic is the one after mushroom way indeed.

**Comment by abyssonym** [comment]
As of version 2, every enemy that gave experience before should give at least 1 experience now. The battle ending prematurely should be fixed too.
