### ISSUE TITLE
Crash in a wiggler fight(Forest Maze)

### ISSUE THREAD

**Issue by Niamek** [abyssonym/smrpg_gbarp#4]
SEED: 1473602340 (The same than issue #3 )

The whole screen stopped animating after an attack or two.

Here is a movie
[Super Mario RPG - Legend of the Seven Stars (USA).1473602340.zip](https://github.com/abyssonym/smrpg_gbarp/files/466055/Super.Mario.RPG.-.Legend.of.the.Seven.Stars.USA.1473602340.zip)

Emulator: SNES9x 1.51 v7

**Comment by Niamek** [comment]
Mack's fight was awesome by the way!

**Comment by abyssonym** [comment]
Thanks. I suspect it's the tiny bomb enemy that crashes the game when it gets its turn.

**Comment by abyssonym** [comment]
I've removed the BB-Bomb from the shuffle pool, as well as a few strange enemies that appear in the intro. There might be other enemies with glitchy effects, but as far as this wiggler battle is concerned, I'd consider the issue resolved.
