### ISSUE TITLE
Enhancement: Making levels up easier?

### ISSUE THREAD

**Issue by Niamek** [abyssonym/smrpg_gbarp#5]
So I played yet another seed, and with my randomized stats, I will need to level up a little bit in order to be able to fight and hope to get some good stats.

I do not mind the randomized stats as it can lead to interesting strategy. But getting 1 or 2 experience even after beating painfully 3 shyster and one red fish hurts.

I come back with #3 too: I need to level up, and yet there are some fight that end prematurely or could even not give experience. That hurt.

**Comment by Niamek** [comment]
By the way, how are stats randomized? I am curious.

**Comment by abyssonym** [comment]
Each character's stats at level 20 is used as a baseline. The level 20 stats are then shuffled between characters and randomized slightly. Then a stat curve is created to decide the stat increases for each level up to 20. Sometimes the curve has a lot of increases in the lower levels, sometimes in the higher levels. Sometimes most of the stat increases are over just a few levels. In any case, it's very difficult to predict, but the objective is to make every character viable at some point in the game, and encourage players to swap party members out.

I'll probably skew the the experience curve to make level ups easier early on, or something.

**Comment by Niamek** [comment]
That's cool. Thank you for the clarification! But does that mean that when fighting the last boss, the stats will almost be like the original stats?

Yes that's one way to do it. Probably the best. The first levels can be long to increase when enemies only gives you one or two EXP and that you can't fight a big group of enemies.

**Comment by abyssonym** [comment]
No, they would be quite different, because Bowser might have some of Peach's stats, Mallow might have some of Bowser's, etc.

**Comment by Niamek** [comment]
Oh yeah I see, not to mention the slight variation from the original stats? Sounds awesome.

Thanks for the clarifications! Would be neat if these kind of information was in the read me.

**Comment by abyssonym** [comment]
I messed around with the experience curve to make early levelups require about half as much experience, though the same amount of experience will be required to reach level 15 and above.
